### ISSUE TITLE
command "Powershell.exe" produced invalid JSON: unexpected end of JSON input

### ISSUE THREAD

**Issue by Kailash-P** [terraform-providers/terraform-provider-external#24]
Hi there,

i am trying to use terraform external provider to run a powershell script

i am not able to pass parameters to the script from terraform.

I use the below code to run the script

variable "file_path" {
    type="string"
    description="Enter the powershell file path"
    default="../../Services/azurerm_iam_role/Powershell_Scripts/test.ps1"
}

data "external" "powershell_test" {
  program = ["Powershell.exe", "${var.file_path}"]

 query = {
    foo = "asdf"
    bar = "Hardcoded"
  }
}

The below is my powershell script file code

# Read stdin as string
$jsonpayload = [Console]::In.ReadLine()

# Convert to JSON
$json = ConvertFrom-Json $jsonpayload

# Access JSON values 
$foo = $json.foo
$bar = $json.bar

while executing the terraform apply i got the below error

 command "Powershell.exe" produced invalid JSON: unexpected end of JSON input

Can you please help me out with a fix or alternate solution.

**Comment by apparentlymart** [comment]
Hi @Kailash-P,

The Terraform team does not have PowerShell expertise so we can't offer any advice on your specific implementation here, but I can offer some additional context that will hopefully help you with debugging:

The error message you saw there indicates that when the `external` data source attempted to parse the data on the standard output stream of the program it did not find valid JSON. "Unexpected end of input" is probably (but not necessarily) telling you that the program didn't produce any output on stdout at all, and so the data source failed to parse the empty string as JSON.

To debug this I would suggest running directly the command you specified in `program` from the shell until you're sure it's generating valid JSON in all cases. You can use I/O redirection to send in data to the program for testing:

```
PowerShell.exe ../../Services/azurerm_iam_role/Powershell_Scripts/test.ps1 <test_data.json
```

The above will use the JSON data from `test_data.json` as the test input. To replicate your Terraform example, this file should contain:

```json
{
  "foo": "asdf",
  "bar": "Hardcoded"
}
```

Once you can see your program is producing valid JSON output on stdout, _then_ you can try it in the external data source and you should find that it then works. Another useful trick for debugging -- if the `external` data source still won't accept what looks like valid output -- is to pipe the output of your program through [`jq`](https://stedolan.github.io/jq/), which will verify that the output is valid JSON and produce a helpful error if not.

Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions, so I'm going to close this. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, with wider expertise, whereas the GitHub issues here are generally monitored only by our few core maintainers.

**Comment by conradj3** [comment]
@apparentlymart  You are absolutely right in your suggestion.  When your using PowerShell/Core to ***Invoke-RestMethod*** or to retrieve data your the return must be a json payload for it to work with the data external provider.  Typically this is the job of the API to return the the proper body. However, whatever your need to use the external provider and PowerShell for make it return a proper json format.  Here is an example of an API call:

**main.tf**
```
data "external" "JwtToken" {
  program = ["Powershell.exe", "./Get-JwtToken.ps1"]

  query = {
    Uri = "https://myawesomeapi/v1/sec-token/users/me/jwt"
    Api = "xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx"  
  }
}
```

**Get-JwtToken.ps1**
```
# Read stdin as string from query settings in data external
$jsonpayload = [Console]::In.ReadLine() # Comment Out for Local testing

# Uncomment for Testing Line 12
    <#
        Local Test Block test.json should look like
        {
        "Apikey": "xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxx",
        "Uri": "https://myawesomeapi/v1/sec-token/users/me/jw"
        }
    #>
#$jsonpayload = Get-Content .\test.json 

# Convert the query json into PsObject
$json = $jsonpayload | ConvertFrom-Json

# Craft IRM Header
$Headers = @{
    'api-key' = $json.ApiKey
}

# Perform IRM with NTLM crdential, using converted query json from the $json PsObject
$res = Invoke-RestMethod -Uri $json.Uri -UseDefaultCredential -Method Get -Headers $Headers

<# 
    At this point the $Res would have been received from your IRM.
    Example: This would be the Jwt Token (Its a Fake)
    $res = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJOYW1lIjoiVGVycmFmb3JtIiwiVXNlciI6Ikp3dFlhISJ9.89aeyOwjkewHskQZzwdaK8L22LmhpCeWlErCdGJqykE" 

    At this point, if Write-Output $res were used, you would get a invalid json error so lets handle that.
#>

# Make Powershell Hashtable and ConvertTo-Json ;)
$ret = @{
    'Bearer' = $res
} | ConvertTo-Json

# Write $ret output.
Write-Output $ret
```

Hope this provides a little more clarity on external data with PowerShell.  Only a couple resources available when this is queried on search engines. Lastly, remember this gets stored in your state file so protect your sensitive data.
