### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by mlehner616** [terraform-providers/terraform-provider-external#29]
I didn't see anything in the works to make this provider compatible with terraform 0.12 so I wanted to get this in for tracking purposes. I understand terraform 0.12 may make some of the functionality of this provider obsolete but it will take a lot of effort to rewrite our configs to eliminate our need for it.

**Comment by apparentlymart** [comment]
We are planning to add Terraform 0.12 support for all providers that are currently installable through `terraform init`, but that's being tracked in an internal checklist just to centralize it so the progress can be tracked more easily. Some providers are harder than others due to their size and the number of different Terraform SDK features they use, but we do intend to update all of them unless we find a very good reason why that is in practical (such as it being archived and us having no means to test it). The `external` provider is a local-only provider, so I don't expect there will be any significant issues with it and it's just a matter of us getting to it.

I'm going to close this not because we don't intend to address it but because this work is being tracked elsewhere (not publicly visible, sadly) and so I expect it'll just get forgotten due to not being on the radar of the teams that are doing this work.

Thanks for reporting this!

**Comment by mlehner616** [comment]
👍

**Comment by jrobison-sb** [comment]
@apparentlymart (or anyone, I guess), can you tell me if the `external` data source currently supports 0.12 as planned?

The reason I ask is that the `external` data source is throwing a `script not found` error in 0.12 and it works fine in 0.11 (the script does exist, and it's chmod 755). I'm happy to open a separate issue for this if the data source is supposed to be working with 0.12. But If it's not, then I'd probably need to move away from this data source.
